type Dataset = {
  id: string; name: string; originalName: string; rowCount: number;
  columnCount: number; fileSizeBytes: number; fileType: string; uploadedAt: Date;
  storagePath: string; columnsJson: string; memorySizeMb: number;
};

export function generateMarkdownReport(
  dataset: Dataset,
  eda: Record<string, unknown>,
  aiSnapshot: Record<string, unknown> | null,
  options: { title?: string; includeAi?: boolean; includeRawStats?: boolean }
): string {
  const title = options.title || `Analysis Report: ${dataset.name}`;
  const now = new Date().toISOString().slice(0, 10);

  let md = `# ${title}\n\n`;
  md += `**Generated:** ${now}  \n`;
  md += `**Dataset:** ${dataset.originalName}  \n`;
  md += `**Dimensions:** ${dataset.rowCount.toLocaleString()} rows × ${dataset.columnCount} columns  \n`;
  md += `**File Size:** ${(dataset.fileSizeBytes / 1024).toFixed(1)} KB  \n\n`;
  md += `---\n\n`;

  md += `## Dataset Overview\n\n`;
  md += `| Metric | Value |\n|--------|-------|\n`;
  md += `| Rows | ${dataset.rowCount.toLocaleString()} |\n`;
  md += `| Columns | ${dataset.columnCount} |\n`;
  md += `| File Type | ${dataset.fileType.toUpperCase()} |\n`;
  md += `| Uploaded | ${new Date(dataset.uploadedAt).toLocaleDateString()} |\n\n`;

  const edaTyped = eda as {
    numericColumns?: { column: string; mean: number; std: number; min: number; max: number; median: number }[];
    categoricalColumns?: { column: string; uniqueCount: number; nullCount: number }[];
    missingValues?: { column: string; count: number; pct: number }[];
    duplicateRows?: number;
  };

  if (edaTyped.numericColumns && edaTyped.numericColumns.length > 0) {
    md += `## Numeric Summary Statistics\n\n`;
    md += `| Column | Mean | Std Dev | Min | Median | Max |\n|--------|------|---------|-----|--------|-----|\n`;
    for (const c of edaTyped.numericColumns) {
      md += `| ${c.column} | ${c.mean.toFixed(2)} | ${c.std.toFixed(2)} | ${c.min.toFixed(2)} | ${c.median.toFixed(2)} | ${c.max.toFixed(2)} |\n`;
    }
    md += `\n`;
  }

  if (edaTyped.categoricalColumns && edaTyped.categoricalColumns.length > 0) {
    md += `## Categorical Columns\n\n`;
    md += `| Column | Unique Values | Null Count |\n|--------|---------------|------------|\n`;
    for (const c of edaTyped.categoricalColumns) {
      md += `| ${c.column} | ${c.uniqueCount} | ${c.nullCount} |\n`;
    }
    md += `\n`;
  }

  if (edaTyped.missingValues && edaTyped.missingValues.length > 0) {
    md += `## Missing Values\n\n`;
    md += `| Column | Missing Count | Missing % |\n|--------|---------------|----------|\n`;
    for (const m of edaTyped.missingValues) {
      md += `| ${m.column} | ${m.count} | ${m.pct.toFixed(1)}% |\n`;
    }
    md += `\n`;
  }

  if (options.includeAi && aiSnapshot) {
    const ai = aiSnapshot as {
      executiveSummary?: string;
      keyFindings?: string[];
      dataQualityScore?: number;
      recommendations?: string[];
    };
    md += `## AI-Powered Insights\n\n`;
    if (ai.executiveSummary) {
      md += `### Executive Summary\n\n${ai.executiveSummary}\n\n`;
    }
    if (ai.dataQualityScore !== undefined) {
      md += `### Data Quality Score: ${ai.dataQualityScore}/100\n\n`;
    }
    if (ai.keyFindings?.length) {
      md += `### Key Findings\n\n`;
      for (const f of ai.keyFindings) md += `- ${f}\n`;
      md += `\n`;
    }
    if (ai.recommendations?.length) {
      md += `### Recommendations\n\n`;
      for (const r of ai.recommendations) md += `- ${r}\n`;
      md += `\n`;
    }
  }

  md += `---\n*Report generated by DataCanvas Analytics Platform*\n`;
  return md;
}
